apiVersion: v1
kind: PersistentVolume
metadata:
  name: tp-pv
  namespace: monitoring-elk
  labels:
    storage: tp-pv
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data-tp
    type: DirectoryOrCreate