apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tp-pvc
  namespace: monitoring-elk
spec:
  storageClassName: standard
  selector:
    matchLabels:
      storage: tp-pv
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany