apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-role
  labels:
    app: fluentd-role
rules:
  - resources:
      - pods
      - namespaces
      - events
    verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""