apiVersion: v1
kind: Service
metadata:
  name: service-kibana
  namespace: monitoring-elk
spec:
  type: NodePort
  selector:
    name: kibana
  ports:
    #--port du service interne
    - port: 5601
    #--- port du conteneur
      targetPort: 5601
      nodePort: 30001 #-- port pour accès externe
      name: kibana-port
