apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: tp-kubernetes
  labels:
    name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0-alpine3.10
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"