apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: tp-kubernetes
  labels:
    name: vote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vote-app
  template:
    metadata:
      labels:
        name: vote-app
    spec:
      containers:
        - name: vote
          image: vote
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
      